version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-89-181.eu-west-1.compute.amazonaws.com
            database: d15t0tf7dlt34c
            user: bahfduwytzxust
            password: 85bbce8f9bc5f111559cd9d8784d84e25e0cde5ad52b5f1e1126cac91e5d4b97
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true